"""
PyMOL scene generation.

Writes portable .pml scripts (relative paths where possible):

  01_overlay.pml              all conditions aligned to baseline, by condition
  02_plddt.pml                all conditions, pLDDT spectrum
  03_per_condition/           one per condition, condition coloured by pLDDT
  04_displacement_putty/      one per condition: cartoon "putty" whose radius +
                              colour encode per-residue Cα displacement vs the
                              baseline (B-factor is overwritten with displacement)
  05_ptm_focus/               one per PTM condition: close-up on the modified
                              residue with surrounding displacement context
  06_clusters.pml             all conditions coloured by structural cluster
  06_clusters/cluster_<k>.pml per-cluster overlay

Displacement scenes work by overwriting each residue's B-factor with its
displacement (Å) through ``alter`` commands, then colouring by B.  This keeps
the scripts self-contained — no external data files are needed in PyMOL.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Dict, List, Optional

log = logging.getLogger("af3bench.pymol")

_PALETTE = [
    "marine", "salmon", "forest", "tv_orange", "slate",
    "hotpink", "cyan", "tv_yellow", "limon", "violet",
    "deeppurple", "teal", "firebrick", "olive", "skyblue",
]

# Cluster colours mirror plots/clusters.py (Okabe-Ito-ish), as PyMOL RGB.
_CLUSTER_RGB = [
    (0.00, 0.45, 0.70), (0.84, 0.37, 0.00), (0.00, 0.62, 0.45),
    (0.80, 0.47, 0.65), (0.90, 0.62, 0.00), (0.34, 0.71, 0.91),
    (0.94, 0.89, 0.26), (0.60, 0.60, 0.60), (0.07, 0.47, 0.20),
    (0.53, 0.13, 0.33),
]

_SETTINGS = [
    "reinitialize",
    "bg_color white",
    "set ray_opaque_background, off",
    "set cartoon_fancy_helices, 1",
    "set cartoon_smooth_loops, 1",
    "set cartoon_side_chain_helper, 1",
    "set depth_cue, 0",
    "set specular, 0.2",
    "set label_size, 16",
    "set label_color, black",
    "set label_outline_color, white",
    "",
]

_FOOTER = [
    "",
    "hide everything",
    "show cartoon, polymer",
    "# show sticks, organic   # ligands",
    "# show spheres, inorganic  # ions",
    "",
    "zoom polymer",
    "orient",
    "",
]


def _header(title: str, note: str = "") -> List[str]:
    lines = [f"# {title}"]
    if note:
        lines.append(f"# {note}")
    lines += ["# Generated by af3bench", "#"]
    return lines + _SETTINGS


def _rel(cif_path: Path, script_dir: Path) -> str:
    try:
        return Path(os.path.relpath(cif_path.resolve(), script_dir.resolve())).as_posix()
    except ValueError:
        return cif_path.resolve().as_posix()


def _ptm_sites(model) -> List[tuple]:
    """Return [(chain_id, resnum, label), ...] for PTMs on a model."""
    out = []
    prot_chain = (model.protein_chain_ids_from_json or
                  (model.ca_chain_ids[:1] if model.ca_chain_ids else ["A"]))[0]
    for lab in getattr(model, "ptm_labels", []) or []:
        digits = "".join(c for c in lab if c.isdigit())
        if digits:
            out.append((prot_chain, int(digits), lab))
    return out


# ---------------------------------------------------------------------------
# Core overlays / pLDDT (unchanged behaviour, kept self-contained)
# ---------------------------------------------------------------------------

def write_pymol_baseline(
    conditions: Dict[str, "object"],
    baseline_name: str,
    output_dir: Path,
    profiles: Optional[Dict[str, dict]] = None,
    cluster_labels: Optional[Dict[str, int]] = None,
    global_disp_max: Optional[float] = None,
    cluster_separation: Optional[dict] = None,
) -> None:
    pymol_dir = output_dir / "pymol"
    pymol_dir.mkdir(parents=True, exist_ok=True)
    per_dir = pymol_dir / "03_per_condition"
    per_dir.mkdir(parents=True, exist_ok=True)

    base_cif = conditions[baseline_name].cif_path.resolve()
    others = [n for n in sorted(conditions) if n != baseline_name]

    # 01 overlay
    lines = _header("AF3 condition overlay vs baseline", f"baseline: {baseline_name}")
    lines += [
        f"load {_rel(base_cif, pymol_dir)}, BASE_{baseline_name}",
        f"color grey70, BASE_{baseline_name}",
        f"set cartoon_transparency, 0.35, BASE_{baseline_name}",
        "",
    ]
    for idx, name in enumerate(others):
        cif = conditions[name].cif_path.resolve()
        color = _PALETTE[idx % len(_PALETTE)]
        lines += [
            f"load {_rel(cif, pymol_dir)}, COND_{name}",
            f"align COND_{name}, BASE_{baseline_name}",
            f"color {color}, COND_{name}",
            "",
        ]
    lines += _FOOTER
    (pymol_dir / "01_overlay.pml").write_text("\n".join(lines) + "\n", encoding="utf-8")

    # 02 plddt
    lines2 = _header("AF3 pLDDT map", "B-factor = pLDDT; blue=high, red=low")
    lines2 += [f"load {_rel(base_cif, pymol_dir)}, BASE_{baseline_name}", ""]
    for name in others:
        cif = conditions[name].cif_path.resolve()
        lines2 += [
            f"load {_rel(cif, pymol_dir)}, COND_{name}",
            f"align COND_{name}, BASE_{baseline_name}",
            "",
        ]
    lines2 += _FOOTER
    lines2 += ["spectrum b, blue_white_red, polymer, minimum=50, maximum=100"]
    (pymol_dir / "02_plddt.pml").write_text("\n".join(lines2) + "\n", encoding="utf-8")

    # 03 per condition (pLDDT)
    for idx, name in enumerate(others):
        cif = conditions[name].cif_path.resolve()
        l3 = _header(f"AF3: {name} vs {baseline_name}",
                     "baseline grey, condition coloured by pLDDT")
        l3 += [
            f"load {_rel(base_cif, per_dir)}, BASE_{baseline_name}",
            f"color grey70, BASE_{baseline_name}",
            f"set cartoon_transparency, 0.35, BASE_{baseline_name}",
            "",
            f"load {_rel(cif, per_dir)}, COND_{name}",
            f"align COND_{name}, BASE_{baseline_name}",
            "",
        ]
        l3 += _FOOTER
        l3 += [
            f"spectrum b, blue_white_red, COND_{name}, minimum=50, maximum=100",
            f"color grey70, BASE_{baseline_name}",
        ]
        (per_dir / f"{name}.pml").write_text("\n".join(l3) + "\n", encoding="utf-8")

    # 04 displacement putty + 05 PTM focus
    if profiles:
        write_pymol_displacement(conditions, baseline_name, profiles,
                                 pymol_dir, global_disp_max)
        write_pymol_ptm_focus(conditions, baseline_name, profiles,
                              pymol_dir, global_disp_max)

    # 06 clusters
    if cluster_labels:
        write_pymol_clusters(conditions, baseline_name, cluster_labels, pymol_dir,
                             cluster_separation=cluster_separation)

    _write_readme(pymol_dir, profiles is not None, bool(cluster_labels))
    _write_render_all(pymol_dir, conditions, baseline_name, profiles, cluster_labels)

    log.info("PyMOL scripts: %s", pymol_dir)


# ---------------------------------------------------------------------------
# Displacement putty
# ---------------------------------------------------------------------------

def _alter_bfactors(obj: str, profile: dict) -> List[str]:
    """Emit ``alter`` commands writing per-residue displacement into B."""
    lines = ["# overwrite B-factor with per-residue Cα displacement (Å)",
             f"alter {obj}, b=0.0"]
    res_numbers = profile.get("res_numbers", [])
    chain_ids = profile.get("chain_ids", [])
    disp = profile.get("disp_mean", [])
    for ch, rn, d in zip(chain_ids, res_numbers, disp):
        try:
            val = float(d)
        except (TypeError, ValueError):
            continue
        if val != val:  # NaN
            continue
        lines.append(f"alter {obj} and chain {ch} and resi {rn}, b={val:.3f}")
    lines.append("rebuild")
    return lines


def write_pymol_displacement(
    conditions: Dict[str, "object"],
    baseline_name: str,
    profiles: Dict[str, dict],
    pymol_dir: Path,
    global_disp_max: Optional[float],
) -> None:
    disp_dir = pymol_dir / "04_displacement_putty"
    disp_dir.mkdir(parents=True, exist_ok=True)
    base_cif = conditions[baseline_name].cif_path.resolve()
    ceil = f"{global_disp_max:.2f}" if global_disp_max else "10.0"

    for name, profile in profiles.items():
        if name not in conditions:
            continue
        cif = conditions[name].cif_path.resolve()
        obj = f"COND_{name}"
        l = _header(
            f"Displacement putty: {name} vs {baseline_name}",
            "tube radius + colour = per-residue Cα displacement (Å); "
            "blue=low, red=high",
        )
        l += [
            f"load {_rel(base_cif, disp_dir)}, BASE_{baseline_name}",
            f"color grey80, BASE_{baseline_name}",
            f"set cartoon_transparency, 0.5, BASE_{baseline_name}",
            "",
            f"load {_rel(cif, disp_dir)}, {obj}",
            f"align {obj}, BASE_{baseline_name}",
            "",
        ]
        l += _alter_bfactors(obj, profile)
        l += [
            "",
            "hide everything",
            f"show cartoon, BASE_{baseline_name} and polymer",
            f"show cartoon, {obj} and polymer",
            f"set cartoon_putty_scale_max, 4, {obj}",
            f"set cartoon_putty_radius, 0.4, {obj}",
            f"cartoon putty, {obj}",
            f"spectrum b, blue_white_red, {obj} and polymer, minimum=0, maximum={ceil}",
        ]
        # mark PTM sites on the moving structure
        for ch, rn, lab in _ptm_sites(conditions[name]):
            sel = f"{obj} and chain {ch} and resi {rn}"
            l += [
                f"show sticks, {sel}",
                f"color magenta, {sel}",
                f"label {sel} and name CA, '{lab}'",
            ]
        l += [
            "",
            f"zoom {obj} and polymer",
            "orient",
            f"# ray 1600, 1200; png {name}_displacement.png, dpi=300",
            "",
        ]
        (disp_dir / f"{name}.pml").write_text("\n".join(l) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# PTM focus close-ups
# ---------------------------------------------------------------------------

def write_pymol_ptm_focus(
    conditions: Dict[str, "object"],
    baseline_name: str,
    profiles: Dict[str, dict],
    pymol_dir: Path,
    global_disp_max: Optional[float],
) -> None:
    ptm_conditions = {
        n: c for n, c in conditions.items()
        if n != baseline_name and _ptm_sites(c)
    }
    if not ptm_conditions:
        return

    focus_dir = pymol_dir / "05_ptm_focus"
    focus_dir.mkdir(parents=True, exist_ok=True)
    base_cif = conditions[baseline_name].cif_path.resolve()
    ceil = f"{global_disp_max:.2f}" if global_disp_max else "10.0"

    for name, cond in ptm_conditions.items():
        profile = profiles.get(name, {})
        cif = cond.cif_path.resolve()
        obj = f"COND_{name}"
        sites = _ptm_sites(cond)
        site_sel = " or ".join(
            f"(chain {ch} and resi {rn})" for ch, rn, _ in sites
        )
        l = _header(
            f"PTM focus: {name}",
            "modified residue (magenta sticks) + baseline equivalent (grey), "
            "neighbourhood coloured by displacement",
        )
        l += [
            f"load {_rel(base_cif, focus_dir)}, BASE_{baseline_name}",
            f"load {_rel(cif, focus_dir)}, {obj}",
            f"align {obj}, BASE_{baseline_name}",
            "",
        ]
        l += _alter_bfactors(obj, profile)
        l += [
            "",
            "hide everything",
            f"show cartoon, {obj} and polymer",
            f"set cartoon_transparency, 0.15, {obj}",
            f"spectrum b, blue_white_red, {obj} and polymer, minimum=0, maximum={ceil}",
            "",
            f"# baseline equivalent residue(s) for reference",
            f"show cartoon, BASE_{baseline_name} and polymer",
            f"set cartoon_transparency, 0.7, BASE_{baseline_name}",
            f"color grey70, BASE_{baseline_name}",
            "",
        ]
        for ch, rn, lab in sites:
            sel = f"{obj} and chain {ch} and resi {rn}"
            bsel = f"BASE_{baseline_name} and chain {ch} and resi {rn}"
            l += [
                f"show sticks, {sel}",
                f"color magenta, {sel}",
                f"util.cnc {sel}",
                f"label {sel} and name CA, '{lab}'",
                f"show sticks, {bsel}",
                f"color grey50, {bsel}",
                f"# show neighbours within 6 A of the PTM",
                f"select near_{rn}, (byres ({obj} within 6 of ({sel}))) and {obj}",
                f"show sticks, near_{rn} and not name C+N+O",
            ]
        if site_sel:
            l += [
                "",
                f"zoom {obj} and ({site_sel}), 8",
                "orient",
                f"# ray 1600, 1200; png {name}_ptm_focus.png, dpi=300",
                "",
            ]
        (focus_dir / f"{name}.pml").write_text("\n".join(l) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# Cluster-coloured scenes
# ---------------------------------------------------------------------------

def write_pymol_clusters(
    conditions: Dict[str, "object"],
    baseline_name: str,
    cluster_labels: Dict[str, int],
    pymol_dir: Path,
    cluster_separation: Optional[dict] = None,
) -> None:
    cl_dir = pymol_dir / "06_clusters"
    cl_dir.mkdir(parents=True, exist_ok=True)

    anchor = baseline_name
    anchor_cif = conditions[anchor].cif_path.resolve()
    names = sorted(conditions)

    # colour-definition preamble
    def _color_defs(script_dir):
        defs = []
        n_clusters = max(cluster_labels.values()) if cluster_labels else 1
        for cid in range(1, n_clusters + 1):
            r, g, b = _CLUSTER_RGB[(cid - 1) % len(_CLUSTER_RGB)]
            defs.append(f"set_color clust{cid}, [{r:.3f}, {g:.3f}, {b:.3f}]")
        return defs

    # 06_clusters.pml — everything, coloured by cluster
    l = _header("AF3 conditions coloured by structural cluster",
                f"alignment anchor: {anchor}")
    l += _color_defs(pymol_dir)
    l += [f"load {_rel(anchor_cif, pymol_dir)}, {anchor}", ""]
    for name in names:
        if name == anchor:
            continue
        cif = conditions[name].cif_path.resolve()
        l += [
            f"load {_rel(cif, pymol_dir)}, {name}",
            f"align {name}, {anchor}",
            "",
        ]
    l += _FOOTER
    for name in names:
        cid = cluster_labels.get(name, 1)
        l.append(f"color clust{cid}, {name}")
    l += [
        "",
        "# clusters group conditions by overall Cα RMSD similarity",
    ]
    if cluster_separation and cluster_separation.get("separation_adequate") is False:
        bm = cluster_separation.get("between_condition_median_rmsd_A")
        nf = cluster_separation.get("within_condition_noise_floor_A")
        l += [
            f"# WARNING: clusters are EXPLORATORY. Between-condition RMSD (median {bm} A)",
            f"# is within the within-condition sampling-noise floor ({nf} A), so these",
            "# colours are NOT robustly separable from AF3 ensemble noise and should not",
            "# be interpreted as distinct conformational states.",
        ]
    (pymol_dir / "06_clusters.pml").write_text("\n".join(l) + "\n", encoding="utf-8")

    # per-cluster overlays
    clusters: Dict[int, List[str]] = {}
    for name, cid in cluster_labels.items():
        clusters.setdefault(cid, []).append(name)

    for cid, members in sorted(clusters.items()):
        members = sorted(members)
        ref = members[0]
        ref_cif = conditions[ref].cif_path.resolve()
        lc = _header(f"Structural cluster {cid}",
                     f"members: {', '.join(members)}")
        lc += [f"load {_rel(ref_cif, cl_dir)}, {ref}", ""]
        for idx, name in enumerate(members[1:]):
            cif = conditions[name].cif_path.resolve()
            color = _PALETTE[idx % len(_PALETTE)]
            lc += [
                f"load {_rel(cif, cl_dir)}, {name}",
                f"align {name}, {ref}",
                f"color {color}, {name}",
                "",
            ]
        lc += _FOOTER
        (cl_dir / f"cluster_{cid}.pml").write_text("\n".join(lc) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# Batch rendering + documentation
# ---------------------------------------------------------------------------

def _write_render_all(
    pymol_dir: Path,
    conditions: Dict[str, "object"],
    baseline_name: str,
    profiles: Optional[Dict[str, dict]],
    cluster_labels: Optional[Dict[str, int]],
) -> None:
    """
    Write render_all.pml that runs every scene headlessly and saves a PNG next
    to each .pml.  Intended for:  pymol -cq render_all.pml

    Each scene script ends with a commented ``ray``/``png`` line; here we drive
    them in batch by @-including the script and issuing the ray/png explicitly.
    """
    others = [n for n in sorted(conditions) if n != baseline_name]
    ptm_conditions = [n for n in others if _ptm_sites(conditions[n])]
    n_clusters = max(cluster_labels.values()) if cluster_labels else 0

    lines = [
        "# render_all.pml - batch-render every af3bench scene to PNG",
        "# Usage:  pymol -cq render_all.pml",
        "#         (requires a PyMOL install on PATH)",
        "set ray_trace_mode, 1",
        "set ray_shadows, 0",
        "",
    ]

    def _block(rel_script: str, png_rel: str):
        return [
            f"@{rel_script}",
            f"ray 1600, 1200",
            f"png {png_rel}, dpi=300",
            "reinitialize",
            "",
        ]

    if profiles:
        for name in profiles:
            if name not in conditions:
                continue
            lines += _block(f"04_displacement_putty/{name}.pml",
                            f"04_displacement_putty/{name}_displacement.png")
        for name in ptm_conditions:
            lines += _block(f"05_ptm_focus/{name}.pml",
                            f"05_ptm_focus/{name}_ptm_focus.png")
    if n_clusters:
        lines += _block("06_clusters.pml", "06_clusters/all_clusters.png")
        for cid in range(1, n_clusters + 1):
            lines += _block(f"06_clusters/cluster_{cid}.pml",
                            f"06_clusters/cluster_{cid}.png")

    (pymol_dir / "render_all.pml").write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_readme(pymol_dir: Path, has_disp: bool, has_clusters: bool) -> None:
    lines = [
        "# PyMOL scenes — af3bench",
        "",
        "Open any scene with:  `pymol <scene>.pml`",
        "Batch-render all scenes to PNG (headless):  `pymol -cq render_all.pml`",
        "",
        "## Scenes",
        "- `01_overlay.pml` — all conditions aligned to baseline, one colour each.",
        "- `02_plddt.pml` — all conditions coloured by pLDDT (blue high, red low).",
        "- `03_per_condition/` — baseline (grey) vs one condition coloured by pLDDT.",
    ]
    if has_disp:
        lines += [
            "- `04_displacement_putty/` — each condition as a cartoon *putty*: tube",
            "  thickness and blue→red colour both encode per-residue Cα displacement",
            "  vs the baseline (Å, written into the B-factor). PTM site = magenta sticks.",
            "- `05_ptm_focus/` — close-up on the modified residue (TPO/SEP), shown as",
            "  magenta sticks beside the baseline equivalent (grey), neighbourhood within",
            "  6 Å as sticks, backbone coloured by displacement.",
        ]
    if has_clusters:
        lines += [
            "- `06_clusters.pml` — every condition coloured by its structural cluster.",
            "- `06_clusters/cluster_<k>.pml` — overlay of the members of one cluster.",
        ]
    lines += [
        "",
        "## Notes",
        "- Displacement is colour-capped at the global 95% CI ceiling so scenes are",
        "  directly comparable across conditions.",
        "- B-factors in scenes 04/05 are **displacement in Å**, not pLDDT.",
        "",
    ]
    (pymol_dir / "README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
